
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.io.FileOutputStream;
import java.io.IOException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Juan Pedro Gil
 */
public class Solicitud extends javax.swing.JFrame {
    public String solicitudActual;
    /**
     * Creates new form Solicitud
     */
    public Solicitud() {
        initComponents();
        cmb_Vehiculo.setVisible(false);
        date_Llegada.setVisible(false);; 
       date_Salida.setVisible(false);
        btn_Ok.setVisible(false);
        cmb_Vehiculo.setVisible(false);
        jScrollPane1.setVisible(false);
        jSeparator1.setVisible(false);
        txt_Actividad.setVisible(false);
        chb_Pernoctado.setVisible(false);
        lbl_Actividad.setVisible(false);
        lbl_Fecha_Llegada.setVisible(false);
        lbl_Fecha_Salida.setVisible(false);
        lbl_Lugar.setVisible(false);
        lbl_Nombre.setVisible(false);
        lbl_Pernoctado.setVisible(false);
        lbl_Puesto.setVisible(false);
        lbl_Vehiculo.setVisible(false);
        spr_Nombre.setVisible(false);
        txt_Lugar.setVisible(false);
        txt_Nombre.setVisible(false);
        txt_Puesto.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Solicitud = new javax.swing.JButton();
        lbl_Nombre = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        spr_Nombre = new javax.swing.JSeparator();
        lbl_Fecha_Salida = new javax.swing.JLabel();
        lbl_Fecha_Llegada = new javax.swing.JLabel();
        date_Llegada = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_Actividad = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Actividad = new javax.swing.JTextArea();
        lbl_Puesto = new javax.swing.JLabel();
        txt_Puesto = new javax.swing.JTextField();
        lbl_Lugar = new javax.swing.JLabel();
        txt_Lugar = new javax.swing.JTextField();
        lbl_Vehiculo = new javax.swing.JLabel();
        cmb_Vehiculo = new javax.swing.JComboBox();
        lbl_Pernoctado = new javax.swing.JLabel();
        btn_Ok = new javax.swing.JButton();
        btn_Cerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        date_Salida = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        chb_Pernoctado = new javax.swing.JCheckBox();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Solicitud.setText("Nueva Solicitud");
        btn_Solicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Solicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 120, 40));

        lbl_Nombre.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbl_Nombre.setText("Nombre");
        getContentPane().add(lbl_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 60, 20));
        getContentPane().add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 290, -1));
        getContentPane().add(spr_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 282, 690, 10));

        lbl_Fecha_Salida.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbl_Fecha_Salida.setText("Fecha de salida");
        getContentPane().add(lbl_Fecha_Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 130, -1));

        lbl_Fecha_Llegada.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbl_Fecha_Llegada.setText("Fecha de llegada");
        getContentPane().add(lbl_Fecha_Llegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 140, -1));
        getContentPane().add(date_Llegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 170, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 352, 700, 10));

        lbl_Actividad.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbl_Actividad.setText("Actividad a realizar");
        getContentPane().add(lbl_Actividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 150, -1));

        txt_Actividad.setColumns(20);
        txt_Actividad.setRows(5);
        jScrollPane1.setViewportView(txt_Actividad);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 670, 80));

        lbl_Puesto.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbl_Puesto.setText("Puesto");
        getContentPane().add(lbl_Puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, -1, -1));
        getContentPane().add(txt_Puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 80, -1));

        lbl_Lugar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbl_Lugar.setText("Lugar");
        getContentPane().add(lbl_Lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, -1));
        getContentPane().add(txt_Lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 90, -1));

        lbl_Vehiculo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbl_Vehiculo.setText("Vehículo");
        getContentPane().add(lbl_Vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 70, -1));

        cmb_Vehiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmb_Vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 150, -1));

        lbl_Pernoctado.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbl_Pernoctado.setText("Pernoctado");
        getContentPane().add(lbl_Pernoctado, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, 90, -1));

        btn_Ok.setBackground(new java.awt.Color(255, 51, 51));
        btn_Ok.setText("OK");
        btn_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OkActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, 130, 30));

        btn_Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_CerrarMouseReleased(evt);
            }
        });
        getContentPane().add(btn_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 40, 40));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 40, 30));
        getContentPane().add(date_Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 140, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        getContentPane().add(chb_Pernoctado, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, -1, -1));

        Fondo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/prueba6.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SolicitudActionPerformed
        // TODO add your handling code here:
        cmb_Vehiculo.setVisible(true);
        date_Llegada.setVisible(true);; 
       date_Salida.setVisible(true);
        btn_Ok.setVisible(true);
        cmb_Vehiculo.setVisible(true);
        jScrollPane1.setVisible(true);
        jSeparator1.setVisible(true);
        txt_Actividad.setVisible(true);
        chb_Pernoctado.setVisible(true);
        lbl_Actividad.setVisible(true);
        lbl_Fecha_Llegada.setVisible(true);
        lbl_Fecha_Salida.setVisible(true);
        lbl_Lugar.setVisible(true);
        lbl_Nombre.setVisible(true);
        lbl_Pernoctado.setVisible(true);
        lbl_Puesto.setVisible(true);
        lbl_Vehiculo.setVisible(true);
        spr_Nombre.setVisible(true);
        txt_Lugar.setVisible(true);
        txt_Nombre.setVisible(true);
        txt_Puesto.setVisible(true);
        //Limpiar
        cmb_Vehiculo.setSelectedIndex(0);
        date_Llegada.setDate(null);
        date_Salida.setDate(null);
        cmb_Vehiculo.setSelectedIndex(0);
        txt_Actividad.setText(null);
        chb_Pernoctado.setText(null);
        txt_Lugar.setText(null);
        txt_Nombre.setText(null);
        txt_Puesto.setText(null);
        txt_Nombre.requestFocus();
    }//GEN-LAST:event_btn_SolicitudActionPerformed

    private void btn_CerrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CerrarMouseReleased
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_btn_CerrarMouseReleased

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        // TODO add your handling code here:
        setExtendedState(JFrame.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_jLabel1MouseReleased

    private void btn_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OkActionPerformed
        // TODO add your handling code here:
        try{
            verificar_excepcion=true;
            validarDatos(true,"");
            insertar_Solicitud();
            CrearPDF pdf=new CrearPDF();
            pdf.generarPDF();
        }catch(ExcepcionDatosIncompletos e){
            if(verificar_excepcion)JOptionPane.showMessageDialog(this, e.getMessage());
            return;
        }catch(DocumentException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }catch(FileNotFoundException es){
            JOptionPane.showMessageDialog(this, es.getMessage());
        }
        
    }//GEN-LAST:event_btn_OkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        CrearPDF pdf=new CrearPDF();
        pdf.pdfFolio("1");
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void insertar_Solicitud(){
        try{
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            String fecha_Salida=sdf.format(date_Salida.getDate().getTime());
            String fecha_Llegada=sdf.format(date_Llegada.getDate().getTime());
            Conexion conexion=new Conexion();
            conexion.conexion();
            String pernoctado="No";
            if(chb_Pernoctado.isSelected()){
                pernoctado="Si";
            }
            System.out.print("insert into Solicitud (Fecha_Salida,Lugar,Nombre,Actividad,Pernoctado,Vehiculo,Puesto,Fecha_Llegada,Estado) values('"+fecha_Salida+"','"+txt_Lugar.getText()+"'"
                + ",'"+txt_Nombre.getText()+"','"+txt_Actividad.getText()+"','"+pernoctado+"','"+cmb_Vehiculo.getSelectedItem().toString()+"'"
                + ",'"+txt_Puesto.getText()+"','"+fecha_Llegada+"','P')");
            boolean insersion=conexion.ejecutar("insert into Solicitud (Fecha_Salida,Lugar,Nombre,Actividad,Pernoctado,Vehiculo,Puesto,Fecha_Llegada,Estado) values('"+fecha_Salida+"','"+txt_Lugar.getText()+"'"
                + ",'"+txt_Nombre.getText()+"','"+txt_Actividad.getText()+"','"+pernoctado+"','"+cmb_Vehiculo.getSelectedItem().toString()+"'"
                + ",'"+txt_Puesto.getText()+"','"+fecha_Llegada+"','P')");
            if(insersion){
                JOptionPane.showMessageDialog(this, "Insersión correcta");
            }else{
                JOptionPane.showMessageDialog(this, "Error al insertar pero no excepción");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    
    //Función para validar los datos que se insertan en el formulario.
    public void validarDatos(boolean verificar_fecha,String cad)throws ExcepcionDatosIncompletos{
        try{
            if(verificar_fecha && date_Llegada.getDate().before(date_Salida.getDate())){
                if(cad.equals("")){
                    cad+="-La fecha de salida es mayor que la de llegada";
                }
                else{
                    cad+="\n-La fecha de salida es mayor que la de llegada";
                }
            }
        }catch(NullPointerException e){
            if(cad.equals("")){
                cad+="-No se ha insertado alguna de las fechas, inserte las fechas de salida y de llegada";
            }
            else{
                cad+="\n-No se ha insertado alguna de las fechas, inserte las fechas de salida y de llegada";
            }
            try{
                verificar_excepcion=false;
                validarDatos(false,cad);
                return;
            }catch(ExcepcionDatosIncompletos ex){
                JOptionPane.showMessageDialog(this, ex.getMessage());
                return;
            }
        }
        if(txt_Actividad.getText().equals("")){
            if(cad.equals("")){
                cad+="-No se ha insertado ninguna actividad, escriba la acitividad y vuelva a intentarlo";
            }
            else{
                cad+="\n-No se ha insertado ninguna actividad, escriba la acitividad y vuelva a intentarlo";
            }
        }
        if(txt_Lugar.getText().equals("")){
            if(cad.equals("")){
                cad+="-No se ha insertado el lugar, escriba el lugar y vuelva a intentarlo";
            }
            else{
                cad+="\n-No se ha insertado el lugar, escriba el lugar y vuelva a intentarlo";
            }
        }
        if(txt_Nombre.getText().equals("")){
            if(cad.equals("")){
                cad+="-No se ha insertado el nombre del epmpleado, escriba el nombre del empleado y vuelva a intentarlo";
            }
            else{
                cad+="\n-No se ha insertado el nombre del epmpleado, escriba el nombre del empleado y vuelva a intentarlo";
            }
        }
        if(txt_Puesto.getText().equals("")){
            if(cad.equals("")){
                cad+="-No se ha insertado el puesto del epmpleado, escriba el nombre del empleado y vuelva a intentarlo";
            }
            else{
                cad+="\n-No se ha insertado el puesto del epmpleado, escriba el nombre del empleado y vuelva a intentarlo";
            }
        }
        if(!cad.equals("")){
            throw new ExcepcionDatosIncompletos(cad);
        }else{
            return;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Solicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Solicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Solicitud.class.getName()).log(java.util.logging.Level.SEVERE, null,ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Solicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Solicitud().setVisible(true);
            }
        });
    }

    private boolean verificar_excepcion=true;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel btn_Cerrar;
    private javax.swing.JButton btn_Ok;
    private javax.swing.JButton btn_Solicitud;
    private javax.swing.JCheckBox chb_Pernoctado;
    private javax.swing.JComboBox cmb_Vehiculo;
    private com.toedter.calendar.JDateChooser date_Llegada;
    private com.toedter.calendar.JDateChooser date_Salida;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_Actividad;
    private javax.swing.JLabel lbl_Fecha_Llegada;
    private javax.swing.JLabel lbl_Fecha_Salida;
    private javax.swing.JLabel lbl_Lugar;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_Pernoctado;
    private javax.swing.JLabel lbl_Puesto;
    private javax.swing.JLabel lbl_Vehiculo;
    private javax.swing.JSeparator spr_Nombre;
    private javax.swing.JTextArea txt_Actividad;
    private javax.swing.JTextField txt_Lugar;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Puesto;
    // End of variables declaration//GEN-END:variables
}
