
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class VenLogin extends javax.swing.JFrame {
   Conexion cbd=new Conexion();
    Connection cn=cbd.conexion();    

    /**
     * Creates new form VenLogin
     */
    int posx,posy;
    public VenLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlcerrar = new javax.swing.JLabel();
        jlmini = new javax.swing.JLabel();
        jlaceptar = new javax.swing.JLabel();
        jlcancelar = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jleusu = new javax.swing.JLabel();
        jlepass = new javax.swing.JLabel();
        jlfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlcerrar.setText(".");
        jlcerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlcerrarMouseClicked(evt);
            }
        });
        getContentPane().add(jlcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 40, 30));

        jlmini.setText(".");
        jlmini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlmini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlminiMouseClicked(evt);
            }
        });
        getContentPane().add(jlmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 40, 30));

        jlaceptar.setText(".");
        jlaceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlaceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlaceptarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlaceptarMousePressed(evt);
            }
        });
        getContentPane().add(jlaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 120, 30));

        jlcancelar.setText(".");
        jlcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlcancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlcancelarMouseClicked(evt);
            }
        });
        getContentPane().add(jlcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 345, 140, 30));

        txtusuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 270, 40));

        txtpassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 258, 270, 40));

        jleusu.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jleusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 260, 20));

        jlepass.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jlepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 305, 270, 20));

        jlfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login2.png"))); // NOI18N
        jlfondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jlfondoMouseDragged(evt);
            }
        });
        jlfondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlfondoMousePressed(evt);
            }
        });
        getContentPane().add(jlfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1002, 475));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Acceder(String usuario,String contraseña){
    
        String roll="";
        String mysql = "SELECT * FROM usuario WHERE Usuario = '"+usuario+"' AND Password = '"+contraseña+"'";
        try{
        java.sql.Statement stmt = cn.createStatement();
        ResultSet rs = stmt.executeQuery(mysql);
        while(rs.next()){  
            roll=rs.getString("Rol_idRol");
        }
        if (roll.equals("1")){
            VentanaAdmin va=new VentanaAdmin();
            va.setVisible(true);
            VentanaAdmin.jladmin.setText(usuario);
            va.pack();
            this.setVisible(false);
        }
        }catch (SQLException ex) {
                        Logger.getLogger(VenLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /*public void validardatos(){
        String us=txtusuario.getText().trim();
        String pa=txtpassword.getText().trim();
        jleusu.setText("");
        jlepass.setText("");
        
        if(us.equals(usu) && pa.equals(pass)){
            JOptionPane.showMessageDialog(this,"Usuario y Contraseña Correctos");
            VentanaAdmin va=new VentanaAdmin();
            va.setVisible(true);
            VentanaAdmin.jladmin.setText(usu);
            this.setVisible(false);
        }
        else if(!us.equals(usu)){
             //JOptionPane.showMessageDialog(this,"Usuario incorrecto");
             jleusu.setText("Usuario incorrecto");
             txtusuario.setText(" ");
             txtusuario.requestFocus();
        }
        
            else if(!pa.equals(pass)){
              //JOptionPane.showMessageDialog(this,"Contraseña incorrecta");
              jlepass.setText("Contraseña incorrecta");
              txtpassword.setText("");
              txtpassword.requestFocus();
                    }
    }*/
    private void jlfondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlfondoMousePressed
     posx=evt.getX();
     posy=evt.getY();
    }//GEN-LAST:event_jlfondoMousePressed

    private void jlfondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlfondoMouseDragged
     int xp=evt.getXOnScreen() -posx;
     int yp=evt.getYOnScreen() -posy;
     this.setLocation(xp,yp);
     
    }//GEN-LAST:event_jlfondoMouseDragged

    private void jlcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarMouseClicked
       System.exit(0);
    }//GEN-LAST:event_jlcerrarMouseClicked

    private void jlminiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlminiMouseClicked
        setExtendedState(JFrame.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_jlminiMouseClicked

    private void jlcancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcancelarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlcancelarMouseClicked

    private void jlaceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlaceptarMouseClicked
       //validardatos();
       String usu=txtusuario.getText();
       String pas=txtpassword.getText();
       Acceder(usu,pas);
    }//GEN-LAST:event_jlaceptarMouseClicked

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            //validardatos();
            String usu=txtusuario.getText();
            String pas=txtpassword.getText();
            Acceder(usu,pas);
        }
    }//GEN-LAST:event_txtpasswordKeyPressed

    private void jlaceptarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlaceptarMousePressed
       
    }//GEN-LAST:event_jlaceptarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VenLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlaceptar;
    private javax.swing.JLabel jlcancelar;
    private javax.swing.JLabel jlcerrar;
    private javax.swing.JLabel jlepass;
    private javax.swing.JLabel jleusu;
    private javax.swing.JLabel jlfondo;
    private javax.swing.JLabel jlmini;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
