
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class VentanaAdmin extends javax.swing.JFrame {
    Conexion cbd=new Conexion();
    Connection cn=cbd.conexion();
    /**
     * Creates new form VentanaAdmin
     */
    int posx,posy;
    ImageIcon agr=new ImageIcon("src//Imagenes//agusu.png");
    ImageIcon mod=new ImageIcon("src//Imagenes//mousu.png");
    ImageIcon busq=new ImageIcon("src//Imagenes//buusu.png");
    ImageIcon elim=new ImageIcon("src//Imagenes//elusu.png");
    ImageIcon agr2=new ImageIcon("src//Imagenes//agusu2.png");
    ImageIcon mod2=new ImageIcon("src//Imagenes//mousu2.png");
    ImageIcon busq2=new ImageIcon("src//Imagenes//buusu2.png");
    ImageIcon elim2=new ImageIcon("src//Imagenes//elusu2.png");
    public VentanaAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        fecha();
        Tausu();
        //txtbuscar.setVisible(false);
        //btnbuscar.setVisible(false);
        //btneliminar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void fecha(){
        Calendar cal= Calendar.getInstance();
        //Date d=new Date();
        String fecha="";
        fecha=cal.get(cal.DATE)+"/"+(cal.get(cal.MONTH)+1)+"/"+cal.get(cal.YEAR);
        jlfecha.setText(fecha+"");
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlagusu = new javax.swing.JLabel();
        jlmousu = new javax.swing.JLabel();
        jlbuusu = new javax.swing.JLabel();
        jleliusu = new javax.swing.JLabel();
        jlmini = new javax.swing.JLabel();
        jlcerrar = new javax.swing.JLabel();
        jladmin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlfecha = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablausu = new javax.swing.JTable();
        btnbuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlagusu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agusu.png"))); // NOI18N
        jlagusu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlagusuMouseClicked(evt);
            }
        });
        getContentPane().add(jlagusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jlmousu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mousu.png"))); // NOI18N
        jlmousu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlmousuMouseClicked(evt);
            }
        });
        getContentPane().add(jlmousu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jlbuusu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buusu.png"))); // NOI18N
        jlbuusu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbuusuMouseClicked(evt);
            }
        });
        getContentPane().add(jlbuusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jleliusu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/elusu.png"))); // NOI18N
        jleliusu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jleliusuMouseClicked(evt);
            }
        });
        getContentPane().add(jleliusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jlmini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlminiMouseClicked(evt);
            }
        });
        getContentPane().add(jlmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 40, 20));

        jlcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlcerrarMouseClicked(evt);
            }
        });
        getContentPane().add(jlcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 50, 20));

        jladmin.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jladmin.setText(".");
        getContentPane().add(jladmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 70, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Administrador");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Fecha: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, -1, -1));

        jlfecha.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlfecha.setText(".");
        getContentPane().add(jlfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 80, -1));

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
        });
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 140, -1));

        tablausu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablausu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 700, 270));

        btnbuscar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        getContentPane().add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Lista de usuarios");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 140, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/admin.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 50, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("Eliminar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Agregar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("Consultar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setText("Modificar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/prueba6.png"))); // NOI18N
        jlFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jlFondoMouseDragged(evt);
            }
        });
        jlFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlFondoMousePressed(evt);
            }
        });
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public DefaultTableModel Tausu(){
        DefaultTableModel tausu=new DefaultTableModel();
       tausu.addColumn("IdUsuario");
       tausu.addColumn("Nombre");
       tausu.addColumn("Apellido");
       tausu.addColumn("Usuario");
       tausu.addColumn("Password");
       tausu.addColumn("Rol_idRol");
       tausu.addColumn("Documentacion");
       //se diferencian en esta sentencia ya que la otra busca todos los resultados de la tabla y esta busca los resultados filtrando mediante el nombre
       String mysql = "SELECT * FROM usuario";
       java.sql.Statement stmt;
      try {
            stmt = cn.createStatement();
            ResultSet rs = stmt.executeQuery(mysql);
            String datos[] = new String[7];
        while(rs.next()){
              
                   datos[0]=rs.getString("idUsuario");
                   datos[1]=rs.getString("Nombre");
                   datos[2]=rs.getString("Apellido");
                   datos[3]=rs.getString("Usuario");
                   datos[4]=rs.getString("Password");
                   datos[5]=rs.getString("Rol_idRol");
                   datos[6]=rs.getString("Documentacion");
                               
               
             tausu.addRow(datos);
             tablausu.setModel(tausu);
            }
            //this.muestraData(rs);
        } catch (SQLException ex) {
                        javax.swing.JOptionPane.showMessageDialog(null, "Error en la consulta");
                        return null;
        }         
       return tausu;
    }
    public void eliminarusuario(String dato){
         String sql="DELETE FROM usuario WHERE idUsuario='"+dato+"'";
              //creamos la instancia
        java.sql.Statement stmt;
        try {
            stmt = cn.createStatement();
            //ejecutamos las sentencias mediante un update puesto que solo actualizaremos la tabla
            stmt.executeUpdate(sql);
            javax.swing.JOptionPane.showMessageDialog(null, "Eliminado correctamente");
            Tausu();
        } catch (SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(null, ex.getErrorCode());
        }
    }
    private void jlminiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlminiMouseClicked
       
       setExtendedState(JFrame.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_jlminiMouseClicked

    private void jlcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarMouseClicked
       System.exit(0); 
    }//GEN-LAST:event_jlcerrarMouseClicked

    private void jlFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlFondoMousePressed
        posx=evt.getX();
        posy=evt.getY(); 
    }//GEN-LAST:event_jlFondoMousePressed

    private void jlFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlFondoMouseDragged
       int xp=evt.getXOnScreen() -posx;
     int yp=evt.getYOnScreen() -posy;
     this.setLocation(xp,yp);
    }//GEN-LAST:event_jlFondoMouseDragged

    private void jlagusuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlagusuMouseClicked
        //ImageIcon agr=new ImageIcon("src//Imagenes//agusu2.png"); 
        jlagusu.setIcon(agr2); 
        jlmousu.setIcon(mod);
        jlbuusu.setIcon(busq);
        jleliusu.setIcon(elim);
                
    }//GEN-LAST:event_jlagusuMouseClicked

    private void jlmousuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlmousuMouseClicked
       jlagusu.setIcon(agr); 
        jlmousu.setIcon(mod2);
        jlbuusu.setIcon(busq);
        jleliusu.setIcon(elim);
    }//GEN-LAST:event_jlmousuMouseClicked

    private void jlbuusuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbuusuMouseClicked
        jlagusu.setIcon(agr); 
        jlmousu.setIcon(mod);
        jlbuusu.setIcon(busq2);
        jleliusu.setIcon(elim);
        //txtbuscar.setVisible(true);
        //btnbuscar.setVisible(true);
        //txtbuscar.requestFocus();
    }//GEN-LAST:event_jlbuusuMouseClicked

    private void jleliusuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jleliusuMouseClicked
       jlagusu.setIcon(agr); 
        jlmousu.setIcon(mod);
        jlbuusu.setIcon(busq);
        jleliusu.setIcon(elim2);
        
        int fila = tablausu.getSelectedRow();
    String elim="";
        if (fila>=0){
            elim=tablausu.getValueAt(fila,0).toString();
            eliminarusuario(elim);
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(null,"Selecciona el dato a eliminar");
        }
    }//GEN-LAST:event_jleliusuMouseClicked

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        DefaultTableModel tausu=new DefaultTableModel();
       tausu.addColumn("IdUsuario");
       tausu.addColumn("Usuario");
       tausu.addColumn("Apellido");
       tausu.addColumn("Usuario");
       tausu.addColumn("Password");
       tausu.addColumn("Rol_idRol");
       tausu.addColumn("Documentacion");
        String datos[] = new String[7];

        String SQL = "SELECT * FROM usuario WHERE idUsuario LIKE '%"+txtbuscar.getText()+"%'"
                        +"OR Nombre LIKE '%"+txtbuscar.getText()+"%'"+"OR Apellido LIKE '%"+txtbuscar.getText()+"%'"
                        +"OR Usuario LIKE '%"+txtbuscar.getText()+"%'";
        java.sql.Statement stmt;
        try {
            stmt = cn.createStatement();
            ResultSet rs = stmt.executeQuery(SQL);

            while(rs.next()){

                datos[0]=rs.getString("idUsuario");
                   datos[1]=rs.getString("Nombre");
                   datos[2]=rs.getString("Apellido");
                   datos[3]=rs.getString("Usuario");
                   datos[4]=rs.getString("Password");
                   datos[5]=rs.getString("Rol_idRol");
                   datos[6]=rs.getString("Documentacion");
                tausu.addRow(datos);
                tablausu.setModel(tausu);
            }
            
            //this.muestraData(rs);
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
    }//GEN-LAST:event_txtbuscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlFondo;
    public static javax.swing.JLabel jladmin;
    private javax.swing.JLabel jlagusu;
    private javax.swing.JLabel jlbuusu;
    private javax.swing.JLabel jlcerrar;
    private javax.swing.JLabel jleliusu;
    private javax.swing.JLabel jlfecha;
    private javax.swing.JLabel jlmini;
    private javax.swing.JLabel jlmousu;
    private javax.swing.JTable tablausu;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
