
import com.itextpdf.text.DocumentException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DenisseYEA
 */
public class VentInforme extends javax.swing.JFrame {

    CrearPDF pdf = new CrearPDF();
    int posx, posy, i, c, folio;
    DefaultTableModel modelo;

    /**
     * Creates new form VentInforme
     */
    public VentInforme() {
        initComponents();
        jTextArea1.enable(false);
        jTextArea2.enable(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jLabel4.setVisible(false);
        i = 0;
        c = 0;
        Solicitud("SELECT O.Folio, S.Nombre FROM solicitud S, oficio_comision O WHERE S.Estado = 'A' AND S.Reporte = '0' AND S.idSolicitud = O.Solicitud_idSolicitud AND O.Monto != 0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jlcerrar = new javax.swing.JLabel();
        jlmini = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jlFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 400, 370));

        jLabel1.setText("Observaciones Viaticos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 510, 120));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 510, 130));

        jLabel2.setText("Observaciones Vehículo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, -1, -1));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solicitudes Aceptadas", "Solicitudes Finalizadas" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 230, -1));

        jlcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlcerrarMouseClicked(evt);
            }
        });
        getContentPane().add(jlcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 50, 20));

        jlmini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlminiMouseClicked(evt);
            }
        });
        getContentPane().add(jlmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 40, 20));

        jButton3.setText("Generar informe");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        jButton4.setText("Consultar Reporte");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        jButton5.setText("Añadir Actividad");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jButton6.setText("Eliminar Actividad");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        jLabel3.setText("BUSCAR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 90, 20));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 170, -1));

        jLabel4.setText("Actividades Realizadas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoadminfin.png"))); // NOI18N
        jlFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jlFondoMouseDragged(evt);
            }
        });
        jlFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlFondoMousePressed(evt);
            }
        });
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlFondoMouseDragged
        int xp = evt.getXOnScreen() - posx;
        int yp = evt.getYOnScreen() - posy;
        this.setLocation(xp, yp);
    }//GEN-LAST:event_jlFondoMouseDragged

    private void jlFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlFondoMousePressed
        posx = evt.getX();
        posy = evt.getY();
    }//GEN-LAST:event_jlFondoMousePressed

    private void jlcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlcerrarMouseClicked

    private void jlminiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlminiMouseClicked

        setExtendedState(JFrame.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_jlminiMouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        switch (jComboBox1.getSelectedIndex()) {
            case 0: {
                Solicitud("SELECT O.Folio, S.Nombre FROM solicitud S, oficio_comision O WHERE S.Estado = 'A' AND S.Reporte = '0' AND S.idSolicitud = O.Solicitud_idSolicitud AND O.Monto != 0");
                jButton3.setVisible(true);
                jButton4.setVisible(false);
                i = 0;
                break;
            }
            case 1: {
                SolicitudR("SELECT I.Id_Informe, O.FOLIO, S.Nombre FROM solicitud S, oficio_comision O, informe I WHERE S.Estado = 'A' AND S.Reporte = '1' AND S.idSolicitud = O.Solicitud_idSolicitud AND I.Solicitud_idSolicitud = S.idSolicitud AND O.Monto != 0");
                jButton4.setVisible(true);
                jButton3.setVisible(false);
                i = 1;
                break;
            }

        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int k = jTable1.getSelectedRow();
        folio = 0;
        if (k >= 0) {
            folio = Integer.parseInt(jTable1.getValueAt(k, 0).toString());
            int filas = jTable1.getRowCount();
            if (filas != 0) {
                for (int j = 0; filas > j; j++) {
                    modelo.removeRow(0);

                }

            }
            modelo = new DefaultTableModel();
            modelo.addColumn("Descripción");
            modelo.addColumn("Precio");
            this.jTable1.setModel(modelo);
            jTextArea1.enable(true);
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/Viaticos", "root", "");

                Statement sentencia = con.createStatement();
                String vehiculo = "";
                ResultSet rs = sentencia.executeQuery("SELECT S.Vehiculo FROM Solicitud S, Oficio_Comision O WHERE S.Estado = 'A' AND S.Reporte = '0' AND S.idSolicitud = O.Solicitud_idSolicitud AND O.Folio = " + folio);
                while (rs.next()) {
                    vehiculo = rs.getString("Vehiculo");
                }
                if (vehiculo != "") {
                    jTextArea2.enable(true);
                    c = 1;
                } else {
                    jTextArea2.enable(false);
                    c = 0;
                }
                jButton1.setVisible(true);
                jButton2.setVisible(true);
                jButton5.setVisible(true);
                jButton6.setVisible(true);
                jButton3.setVisible(false);
                jComboBox1.setVisible(false);
                jLabel3.setVisible(false);
                jTextField1.setVisible(false);
                jLabel4.setVisible(true);
            } catch (SQLException ex) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error en la consulta");

            } catch (ClassNotFoundException e) {
                e.printStackTrace();
            }

        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Seleccionar solicitud");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int s = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if (s == JOptionPane.YES_OPTION) {
            jTextArea1.setText("");
            jTextArea2.setText("");
            jTextArea1.enable(false);
            jTextArea2.enable(false);
            jButton1.setVisible(false);
            jButton2.setVisible(false);
            jButton5.setVisible(false);
            jButton6.setVisible(false);
            jButton3.setVisible(true);
            jComboBox1.setVisible(true);
            jTable1.enable(true);
            jLabel3.setVisible(true);
            jTextField1.setVisible(true);
            jLabel4.setVisible(false);
            Solicitud("SELECT O.Folio, S.Nombre FROM solicitud S, oficio_comision O WHERE S.Estado = 'A' AND S.Reporte = '0' AND S.idSolicitud = O.Solicitud_idSolicitud");
        } else {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int filas = jTable1.getRowCount();
        if (filas == 0) {
            modelo.addRow(new Object[]{"", ""});
        } else if (jTable1.getValueAt(filas - 1, 0) != "" && jTable1.getValueAt(filas - 1, 1) != "") {
            modelo.addRow(new Object[]{"", ""});
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        modelo.removeRow(i);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            int s = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if (s == JOptionPane.YES_OPTION) {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/Viaticos", "root", "");
                String id = "";
                Statement sentencia = con.createStatement();
                ResultSet rs = sentencia.executeQuery("SELECT Solicitud_idSolicitud FROM Oficio_Comision WHERE Folio = " + folio);
                while (rs.next()) {
                    id = rs.getString("Solicitud_idSolicitud");
                }
                if (c == 1) {
                    sentencia.execute("INSERT INTO informe (Observaciones,Observaciones_Vehiculo,Solicitud_idSolicitud) VALUES('" + jTextArea1.getText() + "','" + jTextArea2.getText() + "'," + id + ")");
                } else {
                    sentencia.execute("INSERT INTO informe (Observaciones,Observaciones_Vehiculo,Solicitud_idSolicitud) VALUES('" + jTextArea1.getText() + "',' '," + id + ")");
                }
                sentencia.executeUpdate("UPDATE solicitud SET Reporte = '1' WHERE (idSolicitud = " + id + ")");
                String idInforme = "";
                ResultSet rs2 = sentencia.executeQuery("SELECT MAX(id_informe) AS id_informe FROM informe");
                while (rs2.next()) {
                    idInforme = rs2.getString("id_informe");
                }
                String idGastos = "";
                int filas = jTable1.getRowCount();
                if (filas != 0) {
                    for (int j = 0; filas > j; j++) {
                        sentencia.execute("INSERT INTO gastos (Descripcion,Precio) VALUES('" + jTable1.getValueAt(j, 0).toString() + "','" + jTable1.getValueAt(j, 1).toString() + "')");
                        ResultSet rs3 = sentencia.executeQuery("SELECT MAX(id_gastos) AS id_gastos FROM gastos");
                        while (rs3.next()) {
                            idGastos = rs3.getString("id_gastos");
                        }
                        sentencia.execute("INSERT INTO informe_gastos VALUES(" + idInforme + "," + idGastos + ")");
                    }
                }
                javax.swing.JOptionPane.showMessageDialog(null, "Reporte Generado");
                if (c == 1) {
                    jTextArea1.enable(false);
                    jTextArea2.enable(false);
                    jTable1.enable(false);
                } else {
                    jTextArea1.enable(false);
                    jTable1.enable(false);
                }
            } else {
            }
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error al generar reporte");

        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:       
        try {
            int k = jTable1.getSelectedRow();
            String idInforme = "";
            if (k >= 0) {
                idInforme = jTable1.getValueAt(k, 0).toString();
                pdf.reporte(idInforme);
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Seleccionar Informe");
            }
        } catch (DocumentException ex) {
            Logger.getLogger(VentInforme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        if (i == 1) {
            modelo = new DefaultTableModel() {
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return false;
                }
            };
            modelo.addColumn("ID Informe");
            modelo.addColumn("Folio");
            modelo.addColumn("Nombre");
            this.jTable1.setModel(modelo);
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/Viaticos", "root", "");

                Statement sentencia = con.createStatement();
                ResultSet rs = sentencia.executeQuery("SELECT I.Id_Informe, O.Folio, S.Nombre FROM solicitud S, oficio_comision O, informe I WHERE S.Estado = 'A' AND S.Reporte = '1' AND S.idSolicitud = O.Solicitud_idSolicitud AND I.Solicitud_idSolicitud = S.idSolicitud AND (I.Id_Informe LIKE '%" + jTextField1.getText()
                        + "%' OR O.Folio LIKE '%" + jTextField1.getText() + "%' OR S.Nombre LIKE '%" + jTextField1.getText() + "%') ");

                String solicitud[] = new String[3];
                while (rs.next()) {
                    solicitud[0] = rs.getString("Id_Informe");
                    solicitud[1] = rs.getString("Folio");
                    solicitud[2] = rs.getString("Nombre");
                    modelo.addRow(solicitud);

                }

            } catch (SQLException ex) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error en la consulta");

            } catch (ClassNotFoundException e) {
                e.printStackTrace();
            }//fin del catch
        }
        if (i == 0) {
            modelo = new DefaultTableModel() {
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return false;
                }
            };
            modelo.addColumn("Folio");
            modelo.addColumn("Nombre");
            this.jTable1.setModel(modelo);
            this.jTable1.setModel(modelo);
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/Viaticos", "root", "");

                Statement sentencia = con.createStatement();

                ResultSet rs = sentencia.executeQuery("SELECT O.Folio, S.Nombre FROM solicitud S, oficio_comision O WHERE S.Estado = 'A' AND S.Reporte = '0' AND S.idSolicitud = O.Solicitud_idSolicitud  AND (O.Folio LIKE '%" + jTextField1.getText() + "%'"
                        + "OR S.Nombre LIKE '%" + jTextField1.getText() + "%') ");

                String solicitud[] = new String[2];
                while (rs.next()) {
                    solicitud[0] = rs.getString("Folio");
                    solicitud[1] = rs.getString("Nombre");
                    modelo.addRow(solicitud);
                }

            } catch (SQLException ex) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error en la consulta");

            } catch (ClassNotFoundException e) {
                e.printStackTrace();
            }//fin del catch
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    public void Solicitud(String s) {
        modelo = new DefaultTableModel() {
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        modelo.addColumn("Folio");
        modelo.addColumn("Nombre");
        this.jTable1.setModel(modelo);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/Viaticos", "root", "");

            Statement sentencia = con.createStatement();

            ResultSet rs = sentencia.executeQuery(s);

            String solicitud[] = new String[2];
            while (rs.next()) {
                solicitud[0] = rs.getString("Folio");
                solicitud[1] = rs.getString("Nombre");
                modelo.addRow(solicitud);
            }

        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error en la consulta");

        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }//fin del catch
    }

    public void SolicitudR(String s) {
        modelo = new DefaultTableModel() {
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        modelo.addColumn("ID Informe");
        modelo.addColumn("Folio");
        modelo.addColumn("Nombre");
        this.jTable1.setModel(modelo);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/Viaticos", "root", "");

            Statement sentencia = con.createStatement();

            ResultSet rs = sentencia.executeQuery(s);
            String solicitud[] = new String[3];
            while (rs.next()) {
                solicitud[0] = rs.getString("Id_Informe");
                solicitud[1] = rs.getString("Folio");
                solicitud[2] = rs.getString("Nombre");
                modelo.addRow(solicitud);

            }

        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error en la consulta");

        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }//fin del catch
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentInforme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentInforme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentInforme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentInforme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentInforme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JLabel jlcerrar;
    private javax.swing.JLabel jlmini;
    // End of variables declaration//GEN-END:variables
}
