
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class VentanaSecre extends javax.swing.JFrame {
    Conexion cbd=new Conexion();
    Connection cn=cbd.conexion();
    /**
     * Creates new form VentanaSecre
     */
    int posx,posy;
    ImageIcon nus=new ImageIcon("src//Imagenes//btsoli2.png");
    ImageIcon nus1=new ImageIcon("src//Imagenes//btsoli.png");
    public VentanaSecre() {
        initComponents();
        setLocationRelativeTo(null);
        fecha();
        Tasoli();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void fecha(){
        Calendar cal= Calendar.getInstance();
        //Date d=new Date();
        String fecha="";
        fecha=cal.get(cal.DATE)+"/"+(cal.get(cal.MONTH)+1)+"/"+cal.get(cal.YEAR);
        jlfecha.setText(fecha+"");
    }
    public void Tasoli(){
        DefaultTableModel taso=new DefaultTableModel();
       taso.addColumn("IdSolicitud");
       taso.addColumn("Fecha_Salida");
       taso.addColumn("Lugar");
       taso.addColumn("Nombre");
       taso.addColumn("Actividad");
       taso.addColumn("Pernoctado");
       taso.addColumn("Vehiculo");
       taso.addColumn("Puesto");
       taso.addColumn("Fecha_llegada");
       taso.addColumn("Estado");
       //se diferencian en esta sentencia ya que la otra busca todos los resultados de la tabla y esta busca los resultados filtrando mediante el nombre
       String mysql = "SELECT * FROM solicitud";
       java.sql.Statement stmt;
      try {
            stmt = cn.createStatement();
            ResultSet rs = stmt.executeQuery(mysql);
            String datos[] = new String[10];
        while(rs.next()){
              
                   datos[0]=rs.getString("idSolicitud");
                   datos[1]=rs.getString("Fecha_salida");
                   datos[2]=rs.getString("Lugar");
                   datos[3]=rs.getString("Nombre");
                   datos[4]=rs.getString("Actividad");
                   datos[5]=rs.getString("Pernoctado");
                   datos[6]=rs.getString("Vehiculo");
                   datos[7]=rs.getString("Puesto");
                   datos[8]=rs.getString("Fecha_llegada");
                   datos[9]=rs.getString("Estado");
                               
               
             taso.addRow(datos);
             tablausu.setModel(taso);
            }
            //this.muestraData(rs);
        } catch (SQLException ex) {
                        javax.swing.JOptionPane.showMessageDialog(null, "Error en la consulta");
        }         
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlmini = new javax.swing.JLabel();
        jlcerrar = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jladmin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlfecha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablausu = new javax.swing.JTable();
        jlnuso = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btncerrarsesion = new javax.swing.JButton();
        btn_Imprimir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jlfondo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlmini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlminiMouseClicked(evt);
            }
        });
        getContentPane().add(jlmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 8, 40, 20));

        jlcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlcerrarMouseClicked(evt);
            }
        });
        getContentPane().add(jlcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 8, 50, 20));

        btnbuscar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        getContentPane().add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 178, -1, -1));

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
        });
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 187, 170, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Lista de solicitudes");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 188, 160, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/admin.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 50, -1));

        jladmin.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(jladmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 150, 20));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Fecha: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, -1, -1));

        jlfecha.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(jlfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 80, 20));

        tablausu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablausu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 750, 300));

        jlnuso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btsoli.png"))); // NOI18N
        jlnuso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlnusoMouseClicked(evt);
            }
        });
        getContentPane().add(jlnuso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Imprimir solicitud");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        btncerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrarse.png"))); // NOI18N
        btncerrarsesion.setText("Cerrar sesión");
        btncerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarsesionActionPerformed(evt);
            }
        });
        getContentPane().add(btncerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, -1, -1));

        btn_Imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnaceptar.png"))); // NOI18N
        btn_Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("Agregar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jlfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoadminfin.png"))); // NOI18N
        jlfondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jlfondoMouseDragged(evt);
            }
        });
        jlfondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlfondoMousePressed(evt);
            }
        });
        getContentPane().add(jlfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 550));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setText("Agregar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlminiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlminiMouseClicked

        setExtendedState(JFrame.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_jlminiMouseClicked

    private void jlcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlcerrarMouseClicked

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        DefaultTableModel taso=new DefaultTableModel();
        taso.addColumn("IdSolicitud");
       taso.addColumn("Fecha_Salida");
       taso.addColumn("Lugar");
       taso.addColumn("Nombre");
       taso.addColumn("Actividad");
       taso.addColumn("Pernoctado");
       taso.addColumn("Vehiculo");
       taso.addColumn("Puesto");
       taso.addColumn("Fecha_llegada");
       taso.addColumn("Estado");
        String datos[] = new String[10];

        String SQL = "SELECT * FROM solicitud WHERE idSolicitud LIKE '%"+txtbuscar.getText()+"%'"
        +"OR Nombre LIKE '%"+txtbuscar.getText()+"%'"+"OR Lugar LIKE '%"+txtbuscar.getText()+"%'"
        +"OR Fecha_salida LIKE '%"+txtbuscar.getText()+"%'";
        java.sql.Statement stmt;
        try {
            stmt = cn.createStatement();
            ResultSet rs = stmt.executeQuery(SQL);

            while(rs.next()){

                datos[0]=rs.getString("idSolicitud");
                   datos[1]=rs.getString("Fecha_salida");
                   datos[2]=rs.getString("Lugar");
                   datos[3]=rs.getString("Nombre");
                   datos[4]=rs.getString("Actividad");
                   datos[5]=rs.getString("Pernoctado");
                   datos[6]=rs.getString("Vehiculo");
                   datos[7]=rs.getString("Puesto");
                   datos[8]=rs.getString("Fecha_llegada");
                   datos[9]=rs.getString("Estado");
                taso.addRow(datos);
                tablausu.setModel(taso);
            }

            //this.muestraData(rs);
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error en la busqueda");
        }
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void jlfondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlfondoMousePressed
         posx=evt.getX();
        posy=evt.getY();
    }//GEN-LAST:event_jlfondoMousePressed

    private void jlfondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlfondoMouseDragged
         int xp=evt.getXOnScreen() -posx;
     int yp=evt.getYOnScreen() -posy;
     this.setLocation(xp,yp);
    }//GEN-LAST:event_jlfondoMouseDragged

    private void jlnusoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlnusoMouseClicked

        jlnuso.setIcon(nus);
        NuevaSolicitud ns=new NuevaSolicitud();
        ns.setVisible(true);

    }//GEN-LAST:event_jlnusoMouseClicked

    private void btncerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarsesionActionPerformed
        VenLogin vl=new VenLogin();
        vl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btncerrarsesionActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jlnuso.setIcon(nus1);
        Tasoli();
    }//GEN-LAST:event_formWindowActivated

    private void btn_ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImprimirActionPerformed
        // TODO add your handling code here:
        int fila=-1;
        String id=null;
        try{
            fila=tablausu.getSelectedRow();
            if(fila>=0){
                id=tablausu.getValueAt(fila, 0).toString();
                
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_btn_ImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSecre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSecre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSecre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSecre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSecre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Imprimir;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncerrarsesion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel jladmin;
    private javax.swing.JLabel jlcerrar;
    private javax.swing.JLabel jlfecha;
    private javax.swing.JLabel jlfondo;
    private javax.swing.JLabel jlmini;
    private javax.swing.JLabel jlnuso;
    private javax.swing.JTable tablausu;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
